realuser/urls.py
from django.urls import path

from . import views

app_name = "realuser"
urlpatterns= [
    path('', views.index , name= "index"),
    path('login', views.login_view , name= "login"),
    path('logout', views.logout_view , name= "logout"),
]

student/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('realuser/', include('realuser.urls')),
    
]
 

users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path('',views.index, name = "index"),
    path('<int:couses_id>' , views.do_couses , name = "couses"),
    path('<int:couses_id>/book' , views.book , name = "book"),
    path('<int:couses_id>/debook' , views.debook , name = "debook"),
    path('<int:couses_id>/admun' , views.admun , name = "admun"),
]

realuser/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.base import Model
# Create your models here.

class Couses(models.Model):
    subject = models.CharField(max_length=64)
    term = models.IntegerField()
    couseid = models.IntegerField()
    num_student = models.IntegerField()
    year = models.IntegerField()
    nisit = models.ManyToManyField(User, blank=True)
    status = models.BooleanField(default=True)

    def is_full(self):
        if self.nisit.count() == self.num_student:
            return True
        return False

    def __str__(self):
        return f"{self.id} :Subject {self.subject} | Semmeter {self.term} | Couses ID {self.couseid} | Student {self.num_student} | Year {self.year}"

realuser/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
# Create your views here.

def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("realuser:login"))
    else:
        return render(request, "realuser/index.html")

def login_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("realuser:index"))

    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("realuser:index"))
        else:
            return render(request, "realuser/login.html", {"fail": "Invalid credential"})
    return render(request, "realuser/login.html")

def logout_view(request):
    logout(request)
    messages.success(request, "Logged out.")
    return render(request, "realuser/login.html", {
        "messages": messages.get_messages(request)
    })

users/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
import users 
from django.shortcuts import get_object_or_404, render 
from .models import Couses
from django.urls import reverse

# Create your views here.
def index(request):
    return render(request, "users/index.html",
    {
        "couses" : Couses.objects.all()
    })
def do_couses(request , couses_id):
    
    couses = get_object_or_404(Couses, pk = couses_id)
        
    
    return render(request, "users/couses.html",{
        "couses" : couses,
        "portai" : couses.nisit.all(),
        "check"  : couses.is_full() ,
        "keekon" : couses.nisit.count(),
        

        
        
        
    })
def book(request, couses_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("realuser:login"))

    couses = get_object_or_404(Couses, pk = couses_id)
    if request.user not in couses.nisit.all():
        couses.nisit.add(request.user)
        couses.save()
    return HttpResponseRedirect(reverse("users:couses",args=(couses_id,)))

def debook(request, couses_id):
    couses = get_object_or_404(Couses, pk = couses_id)
    if request.user  in couses.nisit.all():
        couses.nisit.remove(request.user)
        couses.save()
    return HttpResponseRedirect(reverse("users:couses",args=(couses_id,)))

def admun(request, couses_id):
    if request.user.is_superuser:
        count = Couses.objects.get(id = couses_id)
        if count.status:
            count.status = False
            count.save()
        else:
            count.status = True
            count.save()
    return HttpResponseRedirect(reverse("users:couses", args=(couses_id,)))

realuser/templates/realuser/index.html
{% extends "users/layout.html" %}

{% block body %}

    <h1>Welcome, {{ request.user.first_name }}</h1>

    <ul>
        <li>Username: {{ request.user.username }}</li>
        <li>Email: {{ request.user.email }}</li>
    </ul>

    <a href="{% url 'users:index' %}">aLL Courses !</a>
    <br>
    <br>
    <br>
    
    <a href="{% url 'realuser:logout' %}">Log out</a>
{% endblock %}

realuser/templates/realuser/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>Users</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

realuser/templates/realuser/login.html
{% extends "users/layout.html" %}

{% block body %}

    {% if messages %}
        {% for message in messages %}
        <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
    {% endif %}

    <form action="{% url 'realuser:login' %}" method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username">
        <input type="password" name="password" placeholder="Password">
        <input type="submit" value="Login">
    </form>

{% endblock %}

users/templates/users/couses.html
{% extends "users/layout.html" %}

{% block body %}
    <h1>
        COUrSES  {{ couses.id }}
    </h1>
    <u1>
        <li>subject : {{ couses.subject}}</li>
        <li>Semmemster : {{couses.term}}</li>
        <li>Student : {{ keekon }} / {{couses.num_student}}</li>
        <li>Status : {% if couses.status %}
                    Avalible
                    {%else%}
                    Unvalible
                    {% endif %}
        </li>
        
        
   
    </u1>
    {% if request.user.is_superuser %}
    <h3> Student: </h3>
    <ul>
        {% for student in portai %}
        <li>
            {{ student.first_name }} {{ student.last_name }}
        </li>
        {% empty %}
        <li>
            No student
        </li>
        {% endfor %}
    </ul>
    
    {% else %}
   
    {% endif %}
    
    {% if request.user not in portai %}
        {% if couses.status %}
        <p><a href="{% url 'users:book' couses.id %}">Register</a></h3>
        {% else %}
        
        {% endif %}
    {% else %}
    <h1>
        aLRadY rEgisTer </h1>
    <br>
    <p><a href="{% url 'users:debook' couses.id %}">de Register</a>
    
    {% endif %}
    
    <br>
    <br>
    <br>
    <li><a href = "{% url 'users:index' %}">Back to menu</a></li>
    {% if request.user.is_superuser %}
    <li><a href="{% url 'users:admun' couses.id %}">Admin CoMand</a></li>
    {% else %}
   
    {% endif %}
{% endblock %}

users/templates/users/index.html
{% extends "users/layout.html" %}

{% block body %}
    <h1>
        Subject List!
    </h1>
    <ul>
    {% for couses in couses %}
        <li>

            
            <a href = "{% url 'users:couses' couses.id %}">{{ couses }}</a>
        </li>
    {% endfor %}
    
    </ul>
    <br>
    <br>
    <p><a href="{% url 'realuser:index' %}">Back</a>
{% endblock %}

users/templates/users/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            Couses
        </title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>